source 'https://rubygems.org'

gem 'berkshelf'
gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'rake'
gem 'rubocop'
gem 'foodcritic'
gem 'stove'
gem "mime-types", '2.6.2'
gem 'chefspec', '>=4.4.0'
gem 'winrm-transport'
